services:
  vivaply-api:
    build:
      context: ../Vivaply.API
      target: runtime
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:5000"

  vivaply-client:
    build:
      context: ../client
      target: runtime
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:80"

  vivaply-db:
    ports: []
